module.exports = [
  {
    title: "Remnants",
    by: ["kjniemela"],
    year: "2023",
    type: "Album",
    trackCount: 7,
    youtubeUrl: "https://www.youtube.com/watch?v=vnxZEC836bs&list=PLB-DctqV8lTg7buayOhVfj77R3Bxn2Lyo",
    image: "/img/projects/trialbyfire.png",
  },
  {
    title: "Skylands OST",
    by: ["kjniemela", "CardiacShark", "mocqoro", "CRYPTIKiTE"],
    year: "Coming Soon",
    type: "Soundtrack",
    trackCount: 15,
    youtubeUrl: "",
    image: "/img/projects/skylands.png",
  },
  {
    title: "Drifter OST",
    by: ["kjniemela", "G_A_C"],
    year: "2022",
    type: "Soundtrack",
    trackCount: 5,
    youtubeUrl: "https://www.youtube.com/watch?v=9UZE3aA08Mg&list=PLB-DctqV8lTidqf8oDp6kzKwHV9gAYtkh",
    image: "/img/projects/drifter.png",
  },
  {
    title: "The Autumn Court",
    by: ["kjniemela"],
    year: "2024",
    type: "Single",
    trackCount: null,
    youtubeUrl: "https://www.youtube.com/watch?v=zJ6KFy9mZYM",
    image: "/img/music/theautumncourt.jpg",
  },
  {
    title: "Metro Rag",
    by: ["kjniemela"],
    year: "2023",
    type: "Single",
    trackCount: null,
    youtubeUrl: "https://www.youtube.com/watch?v=nTbyLpfXZyo",
    image: "/img/music/metrorag.jpg",
  },
  {
    title: "The Sparrow",
    by: ["kjniemela"],
    year: "2023",
    type: "Single",
    trackCount: null,
    youtubeUrl: "https://www.youtube.com/watch?v=vc9ufvLrOoU",
    image: "/img/music/thesparrow.webp",
  },
  {
    title: "A Glimmer of Hope",
    by: ["kjniemela"],
    year: "2023",
    type: "Single",
    trackCount: null,
    youtubeUrl: "https://www.youtube.com/watch?v=28_yd7JERr0",
    image: "/img/music/aglimmerofhope.jpg",
  },
  {
    title: "The Warrior Comes Home",
    by: ["kjniemela"],
    year: "2023",
    type: "Single",
    trackCount: null,
    youtubeUrl: "https://www.youtube.com/watch?v=vaB0NUEZjPE",
    image: "/img/music/thewarriorcomeshome.jpg",
  },
  {
    title: "Sombre Melody No. 1",
    by: ["kjniemela"],
    year: "2022",
    type: "Single",
    trackCount: null,
    youtubeUrl: "https://www.youtube.com/watch?v=0oPCcUnOVmY",
    image: "/img/music/sombremelodyno1.webp",
  },
];
